# Generated by Django 4.2.7 on 2023-11-29 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'CategoriasVideo',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryTexto',
        ),
        migrations.AlterModelOptions(
            name='categorytexto',
            options={'verbose_name_plural': 'CategoriasTexto'},
        ),
        migrations.RemoveField(
            model_name='texto',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='texto',
            name='link',
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='telas.texto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(related_name='videos', to='telas.categoryvideo'),
        ),
    ]
