# Generated by Django 4.2.7 on 2023-11-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0002_categoryvideo_rename_category_categorytexto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sumario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sumario_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
