# Generated by Django 4.2.7 on 2023-11-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0003_sumario_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
